CREATE TABLE [dbo].[BankAccount]
(
[BankAccountID] [uniqueidentifier] NOT NULL,
[AccountID] [bigint] NOT NULL,
[GLAccountID] [uniqueidentifier] NOT NULL,
[BankName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[BankNumber] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RoutingNumber] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AccountNumber] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[NextCheckNumber] [int] NOT NULL,
[Type] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CompanyLine1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CompanyLine2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CompanyLine3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CompanyLine4] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CompanyLine5] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankLine1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankLine2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankLine3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankLine4] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankLine5] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FractionalNumber] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountOpenDate] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AddressID] [uniqueidentifier] NULL,
[CheckPrintingProfileID] [uniqueidentifier] NULL,
[ContactName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fax] [nvarchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VoucherCompanyLine] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DefaultSignature1PersonID] [uniqueidentifier] NULL,
[DefaultSignature2PersonID] [uniqueidentifier] NULL,
[DepositBatchesByDefault] [bit] NOT NULL,
[AccountNumberDisplay] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CloseDate] [date] NULL,
[CustomFileSettings] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DepositPrintingProfileID] [uniqueidentifier] NULL,
[DepositSlipRoutingNumber] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CreditLimit] [money] NULL,
[AutoClearBankDeposits] [bit] NULL CONSTRAINT [DF__BankAccou__AutoC__0F03239C] DEFAULT ((0)),
[PositivePayFTPHost] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PositivePayFTPUsername] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PositivePayFTPPassword] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PositivePayCustomReportID] [uniqueidentifier] NULL,
[PositivePayFileType] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PositivePayFTPPort] [int] NULL,
[PositivePayFTPPath] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PositivePayFTPFileName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PositivePayConnectionType] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PositivePayLastRunDate] [datetime] NULL,
[ImmediateDestination] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ImmediateDestinationName] [nvarchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ImmediateOrigin] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ImmediateOriginName] [nvarchar] (23) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginatingDFIIdentification] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NextACHNumber] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BankAccount] ADD CONSTRAINT [PK_BankAccount] PRIMARY KEY CLUSTERED  ([BankAccountID], [AccountID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BankAccount] WITH NOCHECK ADD CONSTRAINT [FK_BankAccount_GLAccount] FOREIGN KEY ([GLAccountID], [AccountID]) REFERENCES [dbo].[GLAccount] ([GLAccountID], [AccountID])
GO
ALTER TABLE [dbo].[BankAccount] NOCHECK CONSTRAINT [FK_BankAccount_GLAccount]
GO
