CREATE TABLE [dbo].[Property]
(
[PropertyID] [uniqueidentifier] NOT NULL,
[AccountID] [bigint] NOT NULL,
[ManagerPersonID] [uniqueidentifier] NULL,
[SupervisorPersonID] [uniqueidentifier] NULL,
[CurrentPropertyAccountingPeriodID] [uniqueidentifier] NULL,
[NSFCharge] [money] NOT NULL,
[Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Abbreviation] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Description] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Website] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Owner] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LateFeeGracePeriod] [tinyint] NOT NULL,
[MaximumLateFee] [money] NOT NULL,
[InitialLateFee] [money] NOT NULL,
[AdditionalLateFeePerDay] [money] NOT NULL,
[AssessLateFees] [bit] NOT NULL,
[RentDueDay] [tinyint] NOT NULL,
[PhoneNumber] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fax] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SMTPServerName] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SmtpPortNumber] [int] NULL,
[SmtpUserName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SmtpPassword] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProrationType] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RoundProrationAmount] [bit] NOT NULL,
[NextWorkOrderNumber] [int] NOT NULL,
[RentProrationType] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__Property__RentPr__08CB2759] DEFAULT ('Market Adjusted'),
[RLLEnrolled] [bit] NOT NULL CONSTRAINT [DF__Property__RLLEnr__4475FD0C] DEFAULT ((0)),
[ManagementCompanyVendorID] [uniqueidentifier] NULL,
[AddressID] [uniqueidentifier] NULL,
[IncludeSalesTaxInInvoiceLineItem] [bit] NOT NULL,
[DefaultMOROutstandingBalanceAction] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NSFCashOnlyLimit] [int] NOT NULL,
[NSFCashOnlyMonths] [int] NOT NULL,
[PortalCssUrl] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PortalWorkOrderAssignedToPersonID] [uniqueidentifier] NULL,
[PortalWorkOrderCategoryID] [uniqueidentifier] NULL,
[PortalWorkOrderDaysDue] [int] NULL,
[POApprovalRequirement] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POApprovalBudgetPercent] [decimal] (6, 4) NULL,
[POApprovalTotal] [money] NULL,
[CalendarColor] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PortalWelcomePageHtml] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FacebookPageUrl] [varchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PortalOnlinePaymentType] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DefaultAPBankAccountID] [uniqueidentifier] NULL,
[PortalDefaultApplicantEmailMessage] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PortalDefaultApplicantEmailSubject] [nvarchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LateFeeScheduleID] [uniqueidentifier] NULL,
[MonthToMonthFee] [money] NOT NULL,
[AssignedLeasingAgentPersonID] [uniqueidentifier] NULL,
[PropertyType] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ApplicationTermsAndConditions] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrackLossGainToLease] [bit] NOT NULL,
[ApplicationSubmittedMessage] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ApplicationVerificationDocumentsInstructions] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SMTPRequiresSSL] [bit] NOT NULL,
[SMTPEmailsPerHour] [int] NULL,
[DocumentsDefaultEmailSubject] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DocumentsDefaultEmailMessage] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WorkOrderMessage] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmailProviderType] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ApplicationMaxDaysOut] [int] NULL,
[AssessLateFeesAutomatically] [bit] NOT NULL,
[PushLeaseDocumentsToPortal] [bit] NOT NULL,
[PortalDefaultApplicantWelcomeMessage] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ApplicationSubmittedScript] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AutoApproveScreenedApplicants] [bit] NOT NULL,
[TimeZoneID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MoveOutProrateChargeDistribution] [bit] NOT NULL,
[LegalName] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TaxID] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GuestCardSubmittedMessage] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DefaultPhoneNumberType] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DefaultIDNumberType] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InvoiceRequiresBatchBeforeApproval] [bit] NOT NULL,
[AutoTotalDepositBatches] [bit] NOT NULL,
[DepositInterestFormulaID] [uniqueidentifier] NULL,
[PortalScreeningIntegrationPartnerItemID] [int] NULL,
[PortalScreeningUsername] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PortalScreeningPassword] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ViewablePortalModules] [bigint] NOT NULL,
[DefaultHoldingUnitID] [uniqueidentifier] NULL,
[DefaultLeaseTermID] [uniqueidentifier] NULL,
[Latitude] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Longitude] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ShortDescription] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LongDescription] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LeaseLength] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DrivingDirections] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AutoAdjustMonthToMonthLeaseCharges] [bit] NOT NULL,
[MTMRentChargesOption] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MTMExtendNonRentCharges] [bit] NOT NULL,
[MTMExtendCredits] [bit] NOT NULL,
[MTMFeeChargeType] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MTMStopAtSignedRenewal] [bit] NOT NULL,
[ProrateExpiringAndRenewalLeases] [bit] NOT NULL,
[AirCon] [bit] NOT NULL,
[BroadbandInternet] [bit] NOT NULL,
[Cable] [bit] NOT NULL,
[Electric] [bit] NOT NULL,
[Gas] [bit] NOT NULL,
[Heat] [bit] NOT NULL,
[HotWater] [bit] NOT NULL,
[Satellite] [bit] NOT NULL,
[Sewer] [bit] NOT NULL,
[Telephone] [bit] NOT NULL,
[Trash] [bit] NOT NULL,
[Water] [bit] NOT NULL,
[UtilityPortionIncluded] [decimal] (16, 2) NOT NULL,
[HideOnlineHeader] [bit] NOT NULL,
[AutoPostGPRChangePeriod] [bit] NOT NULL,
[AutoPostGPRNightly] [bit] NOT NULL,
[AutoLostProspectReasonID] [uniqueidentifier] NULL,
[MaxProspectInactiveDays] [int] NULL,
[AutoCreateDocuSignTemplates] [bit] NOT NULL,
[FiscalYearStartMonth] [tinyint] NULL,
[SpecifyRecurringChargePostingDay] [bit] NOT NULL,
[AllowFormerInPortal] [bit] NOT NULL,
[AllowEvictedInPortal] [bit] NOT NULL,
[NoticeToVacateDaysRequired] [int] NOT NULL,
[InsufficientNoticeFeeAmount] [money] NOT NULL,
[EarlyLeaseTerminationFeeType] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EarlyLeaseTerminationFeeAmount] [money] NOT NULL,
[ProrateMoveOutsOnPostRecurringCharges] [bit] NOT NULL,
[DefaultWorkOrderNotes] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OnlineApplicationSurvey1ID] [uniqueidentifier] NULL,
[OnlineApplicationSurvey2ID] [uniqueidentifier] NULL,
[EnableCommunityMembersPortal] [bit] NOT NULL,
[EnableOnlineGuestcard] [bit] NOT NULL,
[EnableOnlineAvailability] [bit] NOT NULL,
[EnableOnlineApplication] [bit] NOT NULL,
[PortalCss] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RegionalManagerPersonID] [uniqueidentifier] NULL,
[OnlineAvailabilityUnitTypeLimit] [int] NULL,
[DefaultAccountingPeriodEndDay] [int] NOT NULL,
[IsArchived] [bit] NOT NULL CONSTRAINT [DF__tmp_ms_xx__IsArc__564B5FDB] DEFAULT ((0)),
[ApplicationSubmittedTitle] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[GuestCardSubmittedTitle] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[GuestCardSubmittedScript] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[County] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__tmp_ms_xx__Count__573F8414] DEFAULT (NULL),
[ForcedLeaseEndDate] [int] NULL,
[NTVDefaultPostMakeReadyWorkOrders] [bit] NOT NULL CONSTRAINT [DF__tmp_ms_xx__NTVDe__5833A84D] DEFAULT ((0)),
[ParentPropertyID] [uniqueidentifier] NULL,
[MarketingName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AllowMultipleRecurringChargePostings] [bit] NOT NULL,
[ImmediatePaymentNotRequiredMessage] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ImmediatePaymentRequiredMessage] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HideGenderField] [bit] NOT NULL,
[InsufficientNoticeFeeType] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MoveInBackDateDays] [int] NULL CONSTRAINT [DF__tmp_ms_xx__MoveI__5927CC86] DEFAULT (NULL),
[MoveInFutureDateDays] [int] NULL CONSTRAINT [DF__tmp_ms_xx__MoveI__5A1BF0BF] DEFAULT (NULL),
[MoveOutBackDateDays] [int] NULL CONSTRAINT [DF__tmp_ms_xx__MoveO__5B1014F8] DEFAULT (NULL),
[MoveOutFutureDateDays] [int] NULL CONSTRAINT [DF__tmp_ms_xx__MoveO__5C043931] DEFAULT (NULL),
[AutoApproveConditionalScreenedApplicants] [bit] NOT NULL,
[AllowUnderEvictionPreleasing] [bit] NOT NULL,
[YearBuilt] [int] NULL CONSTRAINT [DF_Property_YearBuilt_A9BD7435] DEFAULT (NULL),
[DateAcquired] [date] NULL CONSTRAINT [DF_Property_DateAcquired_9223CB51] DEFAULT (NULL),
[DateSold] [date] NULL CONSTRAINT [DF_Property_DateSold_28873CF9] DEFAULT (NULL),
[PurchasePrice] [money] NULL CONSTRAINT [DF_Property_PurchasePrice_63F0C8E6] DEFAULT (NULL),
[SellingPrice] [money] NULL CONSTRAINT [DF_Property_SellingPrice_91AB4BCF] DEFAULT (NULL),
[Market] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_Property_Market_4641CFD7] DEFAULT (NULL),
[MonthToMonthFeeType] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DoNotAllowUnderEvictionPayments] [bit] NOT NULL CONSTRAINT [DF__tmp_ms_xx__DoNot__62B136C0] DEFAULT ((0)),
[PreventClosedPeriodTransactionEdits] [bit] NOT NULL CONSTRAINT [DF__tmp_ms_xx__Preve__63A55AF9] DEFAULT ((0)),
[GuestCardCss] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OnlineAvailabilityCss] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OnlineApplicationCss] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MarketingCss] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MarketingTextResponse] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OnlineAvailabilityUnitUnavailableMessage] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DefaultCancelApplicationReasonForLeavingPickListItemID] [uniqueidentifier] NULL,
[FinalAccountStatementText] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AutomaticLateFeeAssessmentPolicy] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MoveOutProrationPostingDate] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__tmp_ms_xx__MoveO__64997F32] DEFAULT ('Move Out Date'),
[GuestCardForms] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__tmp_ms_xx__Guest__658DA36B] DEFAULT ('Address,Preferences'),
[MarketingPhoneNumber] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LateFeeAssessmentIncludePaymentsOnDay] [bit] NOT NULL,
[AutomaticLateFeePostingDelay] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[KeepOldLeaseLateFeeScheduleForRenewals] [bit] NOT NULL,
[AutocheckDisableOnlinePayments] [bit] NOT NULL,
[PaymentReceiptMessage] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InternalPropertyID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRACSProjectMailID] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRACSCAMailID] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EnableTaxCreditFeatures] [bit] NOT NULL,
[EnableHUDFeatures] [bit] NOT NULL,
[AffordableIsFloating] [bit] NOT NULL,
[MinimumApplicantAge] [int] NOT NULL,
[FormSettingsNoticeOfDefaultReport] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IncludeNonPortalWorkOrders] [bit] NOT NULL,
[TenantRentShouldDeductRentConcessions] [bit] NOT NULL,
[TRACSProjectMailPassword] [nvarchar] (24) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EnableHapLedger] [bit] NOT NULL,
[ScheduledArchiveDate] [datetime] NULL,
[EnableAffordableWaitList] [bit] NOT NULL,
[ApprovedStatusMarketingName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ApprovedStatusMessage] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ConditionallyApprovedStatusMarketingName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ConditionallyApprovedStatusMessage] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PendingStatusMarketingName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PendingStatusMessage] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DeniedStatusMarketingName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DeniedStatusMessage] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TaxCreditReportingPlatform] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TDHCAID] [int] NULL,
[SignLeaseMessage] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmployerIdentificationNumber] [nvarchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TenantIncomeCertifications] [int] NULL,
[DisableDemographicsForForms] [bit] NOT NULL,
[ResidentPortalAppointmentOptions] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[EnableResComm] [bit] NOT NULL,
[ResCommPersonID] [uniqueidentifier] NULL,
[AutoNotices] [bit] NOT NULL,
[HideCitizenField] [bit] NOT NULL,
[AvailabilityHideRent] [bit] NOT NULL,
[NoticeFormLetter120] [uniqueidentifier] NULL,
[NoticeFormLetter90] [uniqueidentifier] NULL,
[NoticeFormLetter60] [uniqueidentifier] NULL,
[NoticeFormLetter30] [uniqueidentifier] NULL,
[NoticeEmailTemplate120] [uniqueidentifier] NULL,
[NoticeEmailTemplate90] [uniqueidentifier] NULL,
[NoticeEmailTemplate60] [uniqueidentifier] NULL,
[NoticeEmailTemplate30] [uniqueidentifier] NULL,
[AutoRecertificationRenewalLease] [bit] NOT NULL,
[ComplianceCenterShowBuildingModule] [bit] NOT NULL,
[ComplianceCenterShowPropertyModule] [bit] NOT NULL,
[ComplianceCenterShowRecertificationModule] [bit] NOT NULL,
[ComplianceCenterShowNAURModule] [bit] NOT NULL,
[ComplianceCenterShowWaitListModule] [bit] NOT NULL,
[ComplianceCenterShowUnitVacancyModule] [bit] NOT NULL,
[ComplianceCenterShowSpecialClaimsModule] [bit] NOT NULL,
[ComplianceCenterShowPropertyDemographicsModule] [bit] NOT NULL,
[VerificationOfFullTimeStudentStatusFormLetterID] [uniqueidentifier] NULL,
[VerificationOfDisabilityFormLetterID] [uniqueidentifier] NULL,
[VerificationOfZeroIncomeFormLetterID] [uniqueidentifier] NULL,
[VerificationOfSelfEmploymentFormLetterID] [uniqueidentifier] NULL,
[VerificationOfIncomeFromEmploymentFormLetterID] [uniqueidentifier] NULL,
[VerificationOfChildSupportFormLetterID] [uniqueidentifier] NULL,
[VerificationOfPublicAssistanceFormLetterID] [uniqueidentifier] NULL,
[VerificationOfMilitaryPayFormLetterID] [uniqueidentifier] NULL,
[VerificationOfPensionFormLetterID] [uniqueidentifier] NULL,
[VerificationOfReceiptOfSocialSecuritySSIFormLetterID] [uniqueidentifier] NULL,
[VerificationOfUnemploymentBenefitsFormLetterID] [uniqueidentifier] NULL,
[VerificationOfAssetsFormLetterID] [uniqueidentifier] NULL,
[AvailbilityDepositViewState] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AvalabilityDepositTextOverride] [nvarchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ComplianceCenterShowPendingCertificationsModule] [bit] NOT NULL,
[DefaultRecertificationsToFirstOfMonth] [bit] NOT NULL,
[ConfirmUnitBaseline] [bit] NOT NULL,
[RentRollLedgerItemTypeID1] [uniqueidentifier] NULL,
[RentRollLedgerItemTypeID2] [uniqueidentifier] NULL,
[RentRollLedgerItemTypeID3] [uniqueidentifier] NULL,
[RentRollLedgerItemTypeID4] [uniqueidentifier] NULL,
[RentRollLedgerItemTypeID5] [uniqueidentifier] NULL,
[PortalWelcomePageHtmlApplicants] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AllowRenewingWithoutOffers] [bit] NOT NULL CONSTRAINT [DF__tmp_ms_xx__Allow__6681C7A4] DEFAULT ((1)),
[AutoPostRecurringChargesDayOfMonth] [int] NULL,
[ComplianceCenterShowHUDReportingModule] [bit] NOT NULL,
[ComplianceCenterShowTaxCreditReportingModule] [bit] NOT NULL,
[GuarantorThresholdType] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[GuarantorThresholdAmount] [money] NULL,
[ApplicationRentableItemsInstructions] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ApplicationGuarantorTermsAndConditions] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EnableStudentSettings] [bit] NOT NULL CONSTRAINT [DF__tmp_ms_xx__Enabl__6775EBDD] DEFAULT ((0)),
[RentersInsuranceMessage] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsDelinquent] [bit] NOT NULL,
[EnableEasyLease] [bit] NOT NULL,
[DefaultRepaymentAgreementTransactionCategoryID] [uniqueidentifier] NULL,
[RoundIncomeOnTics] [bit] NOT NULL,
[PortalWelcomePageHtmlAlwaysShow] [bit] NOT NULL,
[DisableNaurAndUvr] [bit] NOT NULL,
[AvailabilityUnitTypeSortBy] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ShowPropertyWebsiteLink] [bit] NOT NULL,
[AutoCreateCorrections] [bit] NOT NULL,
[OnlyAllowPostingTransactionsTodaysDate] [bit] NOT NULL,
[RenewalOfferMessage] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UseTracsRelease202D] [bit] NOT NULL,
[ComplianceWorkflowOptions] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EnableTwoSalaryAmounts] [bit] NOT NULL,
[TRACSAdministratorPersonID] [uniqueidentifier] NULL,
[AffordableIsAutoCreateHAP] [bit] NOT NULL CONSTRAINT [DF__Property__Afford__6B117297] DEFAULT ((1)),
[AutoPostIntegratedPaymentInPriorPeriodToCurrent] [bit] NOT NULL,
[PetPolicy] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HudOwned] [bit] NOT NULL,
[TRACSVoucherSenderTitle] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRACSVoucherSenderPhoneNumber] [nvarchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TRACSVoucherSenderName] [nvarchar] (45) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MTMDontRound] [bit] NOT NULL CONSTRAINT [DF__Property__MTMDon__5F6AB5C1] DEFAULT ((0)),
[EnableRDFeatures] [bit] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[Property] ADD CONSTRAINT [PK_Property] PRIMARY KEY CLUSTERED  ([PropertyID], [AccountID]) ON [PRIMARY]
GO
