CREATE TABLE [dbo].[Settings]
(
[AccountID] [bigint] NOT NULL,
[AccountsReceivableGLAccountID] [uniqueidentifier] NOT NULL,
[CashSecurityDepositGLAccountID] [uniqueidentifier] NOT NULL,
[CompanyName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Subdomain] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmailHostName] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmailSmtpPortNumber] [int] NULL,
[EmailUserName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmailPassword] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrepaidIncomeGLAccountID] [uniqueidentifier] NOT NULL,
[DepositAccountsPayableGLAccountID] [uniqueidentifier] NOT NULL,
[AccountsPayableGLAccountID] [uniqueidentifier] NOT NULL,
[GrossPotentialRentGLAccountID] [uniqueidentifier] NOT NULL,
[MonthToMonthFeeLedgerItemTypeID] [uniqueidentifier] NOT NULL,
[LossToLeaseLedgerItemTypeID] [uniqueidentifier] NOT NULL,
[GainToLeaseLedgerItemTypeID] [uniqueidentifier] NOT NULL,
[LateFeeLedgerItemTypeID] [uniqueidentifier] NOT NULL,
[NSFChargeLedgerItemTypeID] [uniqueidentifier] NOT NULL,
[AddNewFollowUpTaskWithProspectAdd] [bit] NOT NULL,
[DaysToFollowUpOnProspect] [int] NULL,
[VacantUnitNonResidentAccountPersonID] [uniqueidentifier] NOT NULL,
[RowsReturnedFromSearch] [tinyint] NULL,
[InvoiceAccountingDate] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DefaultAccountingBasis] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[FiscalYearStartMonth] [tinyint] NULL,
[HideZeroValuesInFinancialReports] [bit] NULL,
[OrderChargesByDate] [bit] NULL,
[CMFormerNonZeroBalanceRequried] [bit] NOT NULL CONSTRAINT [DF__Settings__CMForm__65EBFF70] DEFAULT ((0)),
[CMFormerUndisposedDepositRequired] [bit] NOT NULL CONSTRAINT [DF__Settings__CMForm__66E023A9] DEFAULT ((0)),
[CMDelinquentWithoutReasonRequired] [bit] NOT NULL CONSTRAINT [DF__Settings__CMDeli__67D447E2] DEFAULT ((0)),
[CMPrepaidWithoutReasonRequired] [bit] NOT NULL CONSTRAINT [DF__Settings__CMPrep__68C86C1B] DEFAULT ((0)),
[CMMoveResidentsRequired] [bit] NOT NULL CONSTRAINT [DF__Settings__CMMove__69BC9054] DEFAULT ((0)),
[CMRenewedLeasesNotUnderContractRequired] [bit] NOT NULL CONSTRAINT [DF__Settings__CMRene__6AB0B48D] DEFAULT ((0)),
[CHMFormerNonZeroBalanceRequried] [bit] NOT NULL CONSTRAINT [DF__Settings__CHMFor__6BA4D8C6] DEFAULT ((0)),
[CHMFormerUndisposedDepositRequired] [bit] NOT NULL CONSTRAINT [DF__Settings__CHMFor__6C98FCFF] DEFAULT ((0)),
[CHMDelinquentWithoutReasonRequired] [bit] NOT NULL CONSTRAINT [DF__Settings__CHMDel__6D8D2138] DEFAULT ((0)),
[CHMPrepaidWithoutReasonRequired] [bit] NOT NULL CONSTRAINT [DF__Settings__CHMPre__6E814571] DEFAULT ((0)),
[CHUndepositedPaymentsRequired] [bit] NOT NULL CONSTRAINT [DF__Settings__CHUnde__6F7569AA] DEFAULT ((0)),
[CHMoveResidentsRequired] [bit] NOT NULL CONSTRAINT [DF__Settings__CHMove__70698DE3] DEFAULT ((0)),
[CHRenewedLeasesNotUnderContractRequired] [bit] NOT NULL CONSTRAINT [DF__Settings__CHRene__715DB21C] DEFAULT ((0)),
[DistributeCollectionsProportionately] [bit] NOT NULL,
[RLLEmailAddress] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IncludeApprovedPOsInBudgetVariance] [bit] NOT NULL,
[DelinquentRentGLAccountID] [uniqueidentifier] NULL,
[BadDebtWriteOffLedgerItemTypeID] [uniqueidentifier] NULL,
[BadDebtRecoveryLedgerItemTypeID] [uniqueidentifier] NULL,
[PortalCssUrl] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OnLinePaymentLedgerItemTypeID] [uniqueidentifier] NULL,
[RequireFinalAccountStatementApproval] [bit] NOT NULL,
[LineItemDescriptionAutofill] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__tmp_ms_xx__LineI__79949C18] DEFAULT ('Description'),
[ShowOverBudgetExpenseNegativeVariance] [bit] NULL,
[CMNotCompletedPORequired] [bit] NOT NULL,
[CHNotCompletedPORequired] [bit] NOT NULL,
[CompanyID] [uniqueidentifier] NOT NULL,
[DefaultTimeZoneID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DefaultPortalPaymentLedgerItemTypeID] [uniqueidentifier] NOT NULL,
[DefaultPortalDepositLedgerItemTypeID] [uniqueidentifier] NOT NULL,
[CompanyEmailAddress] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PropertyLimit] [int] NOT NULL,
[PaymentProcessorFeesGLAccountID] [uniqueidentifier] NOT NULL,
[ManagementFeesGLAccountID] [uniqueidentifier] NULL,
[RetainedEarningsGLAccountID] [uniqueidentifier] NULL,
[AptexxExternalID] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CMUnpostedPartnerTransactionsRequired] [bit] NOT NULL,
[CHUnpostedPartnerTransactionsRequired] [bit] NOT NULL,
[DefaultProspectSourceID] [uniqueidentifier] NULL,
[SecurityDepositInterestExpenseGLAccountID] [uniqueidentifier] NULL,
[DepositInterestDebitGLAccountID] [uniqueidentifier] NULL,
[NextPurchaseOrderNumber] [int] NOT NULL,
[CollectionsAgencyFeeLedgerItemTypeID] [uniqueidentifier] NULL,
[LossToLeaseGLAccountID] [uniqueidentifier] NOT NULL,
[GainToLeaseGLAccountID] [uniqueidentifier] NOT NULL,
[VendorApprovalSource] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VendorApprovalSourceInsuranceMet] [bit] NOT NULL,
[VendorNotApprovedPurchaseOrders] [bit] NOT NULL,
[VendorNotApprovedInvoices] [bit] NOT NULL,
[VendorNotApprovedPayments] [bit] NOT NULL,
[VendorApprovalSourceW9Or1099Received] [bit] NOT NULL,
[InsufficientNoticeFeeLedgerItemTypeID] [uniqueidentifier] NULL,
[EarlyTerminationFeeLedgerItemTypeID] [uniqueidentifier] NULL,
[AcceleratedRentLedgerItemTypeID] [uniqueidentifier] NULL,
[PriorMonthCollectionsGLAccountID] [uniqueidentifier] NULL,
[PasswordMinimumLength] [int] NOT NULL CONSTRAINT [DF__tmp_ms_xx__Passw__7A88C051] DEFAULT ((5)),
[PasswordExpirationDays] [int] NOT NULL CONSTRAINT [DF__tmp_ms_xx__Passw__7B7CE48A] DEFAULT ((180)),
[PasswordHistory] [int] NOT NULL,
[UseEliminationAccounting] [bit] NOT NULL,
[EliminationAccountingBookID] [uniqueidentifier] NULL,
[NextWorkOrderNumber] [int] NOT NULL CONSTRAINT [DF__tmp_ms_xx__NextW__7C7108C3] DEFAULT ((0)),
[UseGlobalWorkOrderNumbering] [bit] NOT NULL CONSTRAINT [DF__tmp_ms_xx__UseGl__7D652CFC] DEFAULT ((0)),
[FinancialReportHideGLNumber] [bit] NOT NULL CONSTRAINT [DF__tmp_ms_xx__Finan__7E595135] DEFAULT ((0)),
[FinancialReportNegativeFormat] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__tmp_ms_xx__Finan__7F4D756E] DEFAULT ('MinusSign'),
[FinancialReportDecimalPlace] [int] NOT NULL,
[EconomicOccupancySubtractLossGainToLease] [bit] NOT NULL CONSTRAINT [DF__tmp_ms_xx__Econo__004199A7] DEFAULT ((1)),
[CheckVoucherInfo] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Form1099TopTopOffset] [int] NULL CONSTRAINT [DF__tmp_ms_xx__Form1__0135BDE0] DEFAULT (NULL),
[Form1099TopLeftOffset] [int] NULL CONSTRAINT [DF__tmp_ms_xx__Form1__0229E219] DEFAULT (NULL),
[Form1099BottomTopOffset] [int] NULL CONSTRAINT [DF__tmp_ms_xx__Form1__031E0652] DEFAULT (NULL),
[Form1099BottomLeftOffset] [int] NULL CONSTRAINT [DF__tmp_ms_xx__Form1__04122A8B] DEFAULT (NULL),
[PayLeasePmID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PayLeaseKey] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DefaultIncompletePOAutoGeneration] [bit] NOT NULL,
[DefaultIncompletePOAutoGenerationSuffix] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DefaultIncompletePOAutoGenerationAutoApprove] [bit] NOT NULL,
[DefaultIncompletePOAutoGenerationUseOriginalDate] [bit] NOT NULL,
[ExposureControlRenewalMonths] [int] NOT NULL,
[IncludePendingPOsInBudgetVariance] [bit] NOT NULL,
[AutoAdjustInvoiceDates] [bit] NOT NULL,
[DefaultExpenseTypeIDForAPI] [uniqueidentifier] NOT NULL,
[AutoApproveInvoices] [bit] NOT NULL,
[HiddenReports] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReportLogoToInclude] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReportLogoMultipleProperties] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TrafficScoreboardIncludeNonQualified] [bit] NOT NULL,
[AutoExpandGLSummaryEntries] [bit] NOT NULL,
[CheckPrintingPayeeNameSeparator] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[VendorNotApprovedCreateAndApproveVendor] [bit] NOT NULL,
[FinancialReportHideParentGLAccountNumbers] [bit] NOT NULL,
[VendorGets1099] [bit] NOT NULL,
[VendorForm1099Type] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VendorSecondTINNotice] [bit] NULL,
[VendorGrossProceedsPaidToAttorney] [bit] NULL,
[VendorRequiredInsuranceTypes] [int] NOT NULL,
[VendorRequireApproval] [bit] NOT NULL,
[HideIncomeChartSeries] [bit] NOT NULL,
[HideExpensesChartSeries] [bit] NOT NULL,
[AutoApprovePurchaseOrders] [bit] NOT NULL,
[InsuranceExceptionsStartDay] [int] NOT NULL,
[InsuranceExceptionsEndDay] [int] NOT NULL,
[OnlyIncludeApprovedApplicantsForMoveIns] [bit] NOT NULL,
[ManagementFeesIncomeGLAccountID] [uniqueidentifier] NULL,
[MaintenanceStat1] [int] NOT NULL,
[MaintenanceStat2] [int] NOT NULL,
[MaintenanceStat3] [int] NOT NULL,
[MaintenanceStat4] [int] NOT NULL,
[LockoutDate] [date] NULL,
[ProjectNumberPrefix] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NextProjectNumber] [int] NULL,
[ShortCode] [nvarchar] (3) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[DoNotAllowPostingToParentGLAccounts] [bit] NOT NULL,
[RentalAssistanceLedgerItemTypeID] [uniqueidentifier] NULL,
[OnlyShowApprovedJournalEntriesFinancialReporting] [bit] NOT NULL,
[OnlyShowApprovedInvoicesFinancialReporting] [bit] NOT NULL,
[ERCUsername] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ERCPassword] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ERCAPIKey] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CHApproveJournalEntriesRequried] [bit] NOT NULL,
[CMApproveJournalEntriesRequried] [bit] NOT NULL,
[IncludeReportPropertyPageBreak] [bit] NOT NULL,
[RenewalOffersRequireApproval] [bit] NOT NULL,
[RenewalOffersNotAllowedCreateAndApprove] [bit] NOT NULL,
[EnableChatMan] [bit] NOT NULL,
[UtilityReimbursementsGLAccountID] [uniqueidentifier] NULL,
[WorkOrderMaintenanceStatsThreshold1] [int] NOT NULL,
[WorkOrderMaintenanceStatsThreshold2] [int] NULL,
[AccountStatementLogoType] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__Settings__Accoun__4E0B1F95] DEFAULT ('None'),
[ReadyToGoLive] [bit] NOT NULL,
[NewColumn] [int] NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[Settings] ADD CONSTRAINT [PK_Account] PRIMARY KEY CLUSTERED  ([AccountID]) ON [PRIMARY]
GO
