CREATE TABLE [dbo].[Vendor]
(
[VendorID] [uniqueidentifier] NOT NULL,
[AccountID] [bigint] NOT NULL,
[CompanyName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PaymentURL] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gets1099] [bit] NOT NULL,
[Form1099Type] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Form1099RecipientsID] [nvarchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Form1099RecipientsName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecondTINNotice] [bit] NULL,
[NeedsInsurance] [bit] NOT NULL,
[InsuranceExpirationDate] [date] NULL,
[CustomerNumber] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecurringPayments] [bit] NULL,
[GrossProceedsPaidToAttorney] [bit] NOT NULL,
[Summary] [bit] NULL,
[Notes] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TaxRateGroupID] [uniqueidentifier] NULL,
[BeginningBalance] [money] NULL,
[BeginningBalanceYear] [int] NULL,
[GLAccountID] [uniqueidentifier] NULL,
[PrintOnCheckAs] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OneCheckPerInvoice] [bit] NOT NULL,
[InvoiceDaysUntilDue] [int] NULL,
[IsActive] [bit] NOT NULL,
[RequirePurchaseOrder] [bit] NOT NULL,
[HighPriorityPayment] [bit] NOT NULL,
[RequiredInsuranceTypes] [int] NULL,
[Abbreviation] [nvarchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PartnerApproved] [bit] NULL,
[IsOwner] [bit] NOT NULL CONSTRAINT [DF__Vendor__IsOwner__13D2C5B1] DEFAULT ((0)),
[AutoEmailOnApproval] [bit] NULL CONSTRAINT [DF__Vendor__AutoEmai__0E0EFF63] DEFAULT ((0)),
[AutoEmailOnApprovalAddress] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DefaultExpenseTypeID] [uniqueidentifier] NULL,
[IsApproved] [bit] NOT NULL,
[CreatedByPersonID] [uniqueidentifier] NOT NULL,
[BankRoutingNumber] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BankAccountNumber] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InvoiceAlwaysDueOn] [int] NULL,
[EFTPaymentsOnly] [bit] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Vendor] ADD CONSTRAINT [PK_Vendor] PRIMARY KEY CLUSTERED  ([VendorID], [AccountID]) ON [PRIMARY]
GO
